#copy this to logstash
input {
  file {
    type => "users-ws.log"
    path => "C:/Users/tarun/workspace/spring-ms-course/PhotoAppApiUsers/users-ws.log"
  }
  file {
    type => "albums-ws.log"
    path => "C:/Users/tarun/workspace/spring-ms-course/PhotoAppApiAlbums/albums-ws.log"
  }
}

output {
  if [type] == "users-ws.log" {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "users-ws-%{+yyyy.mm.dd}"
    }
  } else if [type] == "albums-ws.log" {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "albums-ws-%{+yyyy.mm.dd}"
    }
  }
  stdout { codec => rubydebug }
}